### ISSUE TITLE
Handover UI/UX

### ISSUE THREAD

**Issue by homura** [ckb-js/nexus#193]
## Todo

- [x] confirm new UI/UX designer @Kirl70
- [x] transfer figma permission
- [x] handover the designs 

## Designs
- [background of Nexus](https://github.com/ckb-js/nexus/blob/proposal/docs/proposal.md) 
- [Wireframe/Hi-Fi](https://www.figma.com/file/x49RWTMPXmN5UgbaCAkraN/wallet?node-id=982-1329&t=3ALrZq1vj7GU7pcH-0) 
- [design system](https://www.figma.com/file/5RPXySjZsbnWtxNjS6pnVl/Nexus-design-system?node-id=2442-2439&t=wN6txMn3gtCaZdPl-0)
- https://github.com/Magickbase/visual-style-guide

**Comment by IronLu233** [comment]
[Wireframe/Hi-Fi](https://www.figma.com/file/x49RWTMPXmN5UgbaCAkraN/wallet?node-id=982-1329&t=3ALrZq1vj7GU7pcH-0) implements in https://github.com/ckb-js/nexus/pull/195

**Comment by homura** [comment]
The design system and Nexus design's link is break now, we should fix it first

**Comment by IronLu233** [comment]
I confirmed with @Kirl70, the handover is finished and currently he doesn't meet any problem.

**Comment by homura** [comment]
Waiting for confirmation from @Kirl70

**Comment by Kirl70** [comment]
Nexus design handover is complete
