### ISSUE TITLE
Support chained transaction

### ISSUE THREAD

**Issue by homura** [ckb-js/nexus#264]
## TODO

- [x] update issue in https://github.com/nervosnetwork/ckb/issues/3950
- [x] update issue in https://github.com/ckb-js/nexus/issues/224
- [x] update issue in https://github.com/ckb-js/nexus/issues/259
- [x] create an issue in Lumos to describe how we plan to support chained transaction
- [ ] implement ckb indexer filter in lumos
- [ ] refactor the old `CkbIndexerCollection` in lumos
- [ ] 🚩 review 2023-04-28
- [ ] upgrade the `TransactionManager`
- [ ] 🚩 review 2023-05-05
- [ ] ~~wrap the `FullOwnershipProvider` with the new transaction manager~~
- [ ] ~~🚩 review 2023-05-08~~

**Comment by zhangyouxin** [comment]
issue in Lumos to track lumos tasks: https://github.com/ckb-js/lumos/issues/501

**Comment by homura** [comment]
We're going to stop the continued integration of FullOwnershipProvider for now, but if you're interested in building chained transactions with pending cells, you can move to the https://github.com/ckb-js/lumos/issues/501
