### ISSUE TITLE
2023-02-27

### ISSUE THREAD

**Issue by homura** [ckb-js/nexus#90]
## Agenda

- review and update the progress in #80 

## Actions

- [x] [code] continue and finish #89, exposed as RPC methods 
- [x] [code] make the https://github.com/ckb-js/nexus/issues/83 works with testnet
- [x] [code] design and implement an event pubsub module to handle events, e.g. `networkChanged`
- [x] [code] make the Nervos DAO dApp works with testnet
  - [x] show deposited/withdrawed cells
  - [x] deposit/withdraw/unlock
  - [x] works with Nexus, `wallet_enable`, `getOffChainLocks`, `getLiveCells`, `signTransaction`
- [ ] [UI/UX] design system for Nexus
- [x] [UI/UX] make network edtiable
- [x] [code] review and merge #84 
- [x] [code] https://github.com/ckb-js/lumos/issues/487 

## Other Notes
